/*
    SPDX-FileCopyrightText: 2025 Du Yijie <nathandu@outlook.com>

    SPDX-License-Identifier: GPL-3.0-or-later
*/
#include "Descriptions.h"

#include <QStringLiteral>
#include <qcontainerfwd.h>
#include <qstringliteral.h>

const QHash<QString, KLocalizedString> featureTagDescriptions{
    {QStringLiteral("aalt"), ki18n("Access All Alternates")},
    {QStringLiteral("abvf"), ki18n("Above-base Forms")},
    {QStringLiteral("abvm"), ki18n("Above-base Mark Positioning")},
    {QStringLiteral("abvs"), ki18n("Above-base Substitutions")},
    {QStringLiteral("afrc"), ki18n("Alternative Fractions")},
    {QStringLiteral("akhn"), ki18n("Akhand")},
    {QStringLiteral("apkn"), ki18n("Kerning for Alternate Proportional Widths")},
    {QStringLiteral("blwf"), ki18n("Below-base Forms")},
    {QStringLiteral("blwm"), ki18n("Below-base Mark Positioning")},
    {QStringLiteral("blws"), ki18n("Below-base Substitutions")},
    {QStringLiteral("calt"), ki18n("Contextual Alternates")},
    {QStringLiteral("case"), ki18n("Case-sensitive Forms")},
    {QStringLiteral("ccmp"), ki18n("Glyph Composition / Decomposition")},
    {QStringLiteral("cfar"), ki18n("Conjunct Form After Ro")},
    {QStringLiteral("chws"), ki18n("Contextual Half-width Spacing")},
    {QStringLiteral("cjct"), ki18n("Conjunct Forms")},
    {QStringLiteral("clig"), ki18n("Contextual Ligatures")},
    {QStringLiteral("cpct"), ki18n("Centered CJK Punctuation")},
    {QStringLiteral("cpsp"), ki18n("Capital Spacing")},
    {QStringLiteral("cswh"), ki18n("Contextual Swash")},
    {QStringLiteral("curs"), ki18n("Cursive Positioning")},
    {QStringLiteral("cv01"), ki18n("Character Variant %1")},
    {QStringLiteral("c2pc"), ki18n("Petite Capitals From Capitals")},
    {QStringLiteral("c2sc"), ki18n("Small Capitals From Capitals")},
    {QStringLiteral("dist"), ki18n("Distances")},
    {QStringLiteral("dlig"), ki18n("Discretionary Ligatures")},
    {QStringLiteral("dnom"), ki18n("Denominators")},
    {QStringLiteral("dtls"), ki18n("Dotless Forms")},
    {QStringLiteral("expt"), ki18n("Expert Forms")},
    {QStringLiteral("falt"), ki18n("Final Glyph on Line Alternates")},
    {QStringLiteral("fin2"), ki18n("Terminal Forms #2")},
    {QStringLiteral("fin3"), ki18n("Terminal Forms #3")},
    {QStringLiteral("fina"), ki18n("Terminal Forms")},
    {QStringLiteral("flac"), ki18n("Flattened Accent Forms")},
    {QStringLiteral("frac"), ki18n("Fractions")},
    {QStringLiteral("fwid"), ki18n("Full Widths")},
    {QStringLiteral("half"), ki18n("Half Forms")},
    {QStringLiteral("haln"), ki18n("Halant Forms")},
    {QStringLiteral("halt"), ki18n("Alternate Half Widths")},
    {QStringLiteral("hist"), ki18n("Historical Forms")},
    {QStringLiteral("hkna"), ki18n("Horizontal Kana Alternates")},
    {QStringLiteral("hlig"), ki18n("Historical Ligatures")},
    {QStringLiteral("hngl"), ki18n("Hangul")},
    {QStringLiteral("hojo"), ki18n("Hojo Kanji Forms (JIS X 0212-1990 Kanji Forms)")},
    {QStringLiteral("hwid"), ki18n("Half Widths")},
    {QStringLiteral("init"), ki18n("Initial Forms")},
    {QStringLiteral("isol"), ki18n("Isolated Forms")},
    {QStringLiteral("ital"), ki18n("Italics")},
    {QStringLiteral("jalt"), ki18n("Justification Alternates")},
    {QStringLiteral("jp78"), ki18n("JIS78 Forms")},
    {QStringLiteral("jp83"), ki18n("JIS83 Forms")},
    {QStringLiteral("jp90"), ki18n("JIS90 Forms")},
    {QStringLiteral("jp04"), ki18n("JIS2004 Forms")},
    {QStringLiteral("kern"), ki18n("Kerning")},
    {QStringLiteral("lfbd"), ki18n("Left Bounds")},
    {QStringLiteral("liga"), ki18n("Standard Ligatures")},
    {QStringLiteral("ljmo"), ki18n("Leading Jamo Forms")},
    {QStringLiteral("lnum"), ki18n("Lining Figures")},
    {QStringLiteral("locl"), ki18n("Localized Forms")},
    {QStringLiteral("ltra"), ki18n("Left-to-right Alternates")},
    {QStringLiteral("ltrm"), ki18n("Left-to-right Mirrored Forms")},
    {QStringLiteral("mark"), ki18n("Mark Positioning")},
    {QStringLiteral("med2"), ki18n("Medial Forms #2")},
    {QStringLiteral("medi"), ki18n("Medial Forms")},
    {QStringLiteral("mgrk"), ki18n("Mathematical Greek")},
    {QStringLiteral("mkmk"), ki18n("Mark to Mark Positioning")},
    {QStringLiteral("mset"), ki18n("Mark Positioning via Substitution")},
    {QStringLiteral("nalt"), ki18n("Alternate Annotation Forms")},
    {QStringLiteral("nlck"), ki18n("NLC Kanji Forms")},
    {QStringLiteral("nukt"), ki18n("Nukta Forms")},
    {QStringLiteral("numr"), ki18n("Numerators")},
    {QStringLiteral("onum"), ki18n("Oldstyle Figures")},
    {QStringLiteral("opbd"), ki18n("Optical Bounds")},
    {QStringLiteral("ordn"), ki18n("Ordinals")},
    {QStringLiteral("ornm"), ki18n("Ornaments")},
    {QStringLiteral("palt"), ki18n("Proportional Alternate Widths")},
    {QStringLiteral("pcap"), ki18n("Petite Capitals")},
    {QStringLiteral("pkna"), ki18n("Proportional Kana")},
    {QStringLiteral("pnum"), ki18n("Proportional Figures")},
    {QStringLiteral("pref"), ki18n("Pre-base Forms")},
    {QStringLiteral("pres"), ki18n("Pre-base Substitutions")},
    {QStringLiteral("pstf"), ki18n("Post-base Forms")},
    {QStringLiteral("psts"), ki18n("Post-base Substitutions")},
    {QStringLiteral("pwid"), ki18n("Proportional Widths")},
    {QStringLiteral("qwid"), ki18n("Quarter Widths")},
    {QStringLiteral("rand"), ki18n("Randomize")},
    {QStringLiteral("rclt"), ki18n("Required Contextual Alternates")},
    {QStringLiteral("rkrf"), ki18n("Rakar Forms")},
    {QStringLiteral("rlig"), ki18n("Required Ligatures")},
    {QStringLiteral("rphf"), ki18n("Reph Form")},
    {QStringLiteral("rtbd"), ki18n("Right Bounds")},
    {QStringLiteral("rtla"), ki18n("Right-to-left Alternates")},
    {QStringLiteral("rtlm"), ki18n("Right-to-left Mirrored Forms")},
    {QStringLiteral("ruby"), ki18n("Ruby Notation Forms")},
    {QStringLiteral("rvrn"), ki18n("Required Variation Alternates")},
    {QStringLiteral("salt"), ki18n("Stylistic Alternates")},
    {QStringLiteral("sinf"), ki18n("Scientific Inferiors")},
    {QStringLiteral("size"), ki18n("Optical size")},
    {QStringLiteral("smcp"), ki18n("Small Capitals")},
    {QStringLiteral("smpl"), ki18n("Simplified Forms")},
    {QStringLiteral("ss01"), ki18n("Stylistic Set %1")},
    {QStringLiteral("ssty"), ki18n("Math Script-style Alternates")},
    {QStringLiteral("stch"), ki18n("Stretching Glyph Decomposition")},
    {QStringLiteral("subs"), ki18n("Subscript")},
    {QStringLiteral("sups"), ki18n("Superscript")},
    {QStringLiteral("swsh"), ki18n("Swash")},
    {QStringLiteral("titl"), ki18n("Titling")},
    {QStringLiteral("tjmo"), ki18n("Trailing Jamo Forms")},
    {QStringLiteral("tnam"), ki18n("Traditional Name Forms")},
    {QStringLiteral("tnum"), ki18n("Tabular Figures")},
    {QStringLiteral("trad"), ki18n("Traditional Forms")},
    {QStringLiteral("twid"), ki18n("Third Widths")},
    {QStringLiteral("unic"), ki18n("Unicase")},
    {QStringLiteral("valt"), ki18n("Alternate Vertical Metrics")},
    {QStringLiteral("vapk"), ki18n("Kerning for Alternate Proportional Vertical Metrics")},
    {QStringLiteral("vatu"), ki18n("Vattu Variants")},
    {QStringLiteral("vchw"), ki18n("Vertical Contextual Half-width Spacing")},
    {QStringLiteral("vert"), ki18n("Vertical Alternates")},
    {QStringLiteral("vhal"), ki18n("Alternate Vertical Half Metrics")},
    {QStringLiteral("vjmo"), ki18n("Vowel Jamo Forms")},
    {QStringLiteral("vkna"), ki18n("Vertical Kana Alternates")},
    {QStringLiteral("vkrn"), ki18n("Vertical Kerning")},
    {QStringLiteral("vpal"), ki18n("Proportional Alternate Vertical Metrics")},
    {QStringLiteral("vrt2"), ki18n("Vertical Alternates and Rotation")},
    {QStringLiteral("vrtr"), ki18n("Vertical Alternates for Rotation")},
    {QStringLiteral("zero"), ki18n("Slashed Zero")},
};

const QHash<QString, KLocalizedString> axisDescriptions{
    {QStringLiteral("ital"), ki18n("Italic")},
    {QStringLiteral("opsz"), ki18n("Optical Size")},
    {QStringLiteral("slnt"), ki18n("Slant")},
    {QStringLiteral("wdth"), ki18n("Width")},
    {QStringLiteral("wght"), ki18nc("Thickness of font outlines", "Weight")},
};
